const myOldAnimeData = [
    {
        id: "dandadan",
        title: "DanDaDan",
        img: "https://s4.anilist.co/custom/bg/171018-0uL0Jq0TjIqP.jpg",
        genre: "Action, Comedy, Supernatural",
        type: "TV Series",
        status: "Ongoing",
        totalEps: 12,
        Trend: "T",
        score: "8.8",
        synopsis: "Momo Ayase strikes up an unusual friendship with her school's UFO fanatic, whom she nicknames 'Okarun' because he has a name that is not to be spoken. While Momo believes in spirits, she thinks aliens are nothing but nonsense. Her new friend, meanwhile, thinks the exact opposite. To settle matters, the two set out to prove each other wrong."
    },
    {
        id: "gachiakuta",
        title: "Gachiakuta",
        img: "https://s4.anilist.co/custom/bg/178872-H0gRMg0J4H2c.jpg",
        genre: "Action, Fantasy, Shonen",
        type: "TV Series",
        status: "Upcoming",
        totalEps: 12,
        Trend: "T",
        score: "N/A",
        synopsis: "Rudo lives in the slums of a floating town, where the poor scrape by in the shadow of the rich who live a luxurious life. When he is framed for a crime he didn't commit, he is thrown into the Abyss—a wasteland where society dumps its trash. There, he discovers dangerous powers to take his revenge."
    },
    {
        id: "chainsawmanmovie1",
        title: "Chainsaw Man Movie: Reze Arc",
        img: "https://s4.anilist.co/custom/bg/171868-y7fP0YcW8O3m.jpg",
        genre: "Action, Supernatural, Shonen",
        type: "Movie",
        status: "Upcoming",
        totalEps: 1,
        Trend: "T",
        score: "N/A",
        synopsis: "Denji’s heart is stolen by a mysterious and explosive new girl named Reze. As their romance blossoms, Denji quickly learns that in the world of Devils, love is a battlefield, and Reze might just be the most dangerous opponent he has ever faced."
    },
    {
        id: "dicam",
        title: "Demon Slayer: Infinity Castle Arc",
        img: "https://s4.anilist.co/custom/bg/178869-7wF8Yn6R2u5Q.jpg",
        genre: "Action, Historical, Supernatural",
        type: "Movie",
        status: "Upcoming",
        totalEps: 1,
        Trend: "T",
        score: "N/A",
        synopsis: "The ultimate battle begins. The Demon Slayer Corps plunges into the shifting, gravity-defying Infinite Castle to confront Muzan Kibutsuji and the remaining Upper Rank demons in an all-out war for the fate of humanity."
    },
    {
        id: "demonslayer",
        title: "Demon Slayer: Kimetsu no Yaiba",
        img: "https://s4.anilist.co/custom/bg/101922-WbsB0cQO6p2Q.jpg",
        genre: "Action, Historical, Supernatural",
        type: "TV Series",
        status: "Completed",
        seasons: [26, 11, 11, 8],
        Trend: "T",
        score: "8.5",
        synopsis: "Ever since the death of his father, the burden of supporting the family has fallen upon Tanjirou Kamado. Tragedy strikes when he returns home to find his family slaughtered by a demon, with his sister Nezuko turned into a bloodthirsty demon herself. Tanjirou swears to avenge his family and cure his sister."
    },
    {
        id: "frieren",
        title: "Frieren: Beyond Journey's End",
        img: "https://s4.anilist.co/custom/bg/154587-8sF624Xz6t0C.jpg",
        genre: "Adventure, Drama, Fantasy",
        type: "TV Series",
        status: "Completed",
        totalEps: 28,
        Trend: "T",
        score: "9.3",
        synopsis: "The demon king has been defeated, and the victorious hero party returns home before disbanding. The four—mage Frieren, hero Himmel, priest Heiter, and warrior Eisen—reminisce about their decade-long journey. For elves like Frieren, however, a decade is but a fleeting moment. She sets out on a new journey to understand what life means to the humans she travels with."
    },
    {
        id: "deathnote",
        title: "Death Note",
        img: "https://s4.anilist.co/custom/bg/1535-q1a7VpZJk0gW.jpg",
        genre: "Mystery, Psychological, Thriller",
        type: "TV Series",
        status: "Completed",
        totalEps: 37,
        Trend: "N",
        score: "8.6",
        synopsis: "Light Yagami is a brilliant student who stumbles across a mystical notebook: the 'Death Note'. The notebook claims that if you write a person's name within its pages while picturing their face, they will die. Light decides to use the notebook to rid the world of criminals, but a legendary detective known only as 'L' stands in his way."
    },
    {
        id: "fullmetalalchemistbrotherhood",
        title: "Fullmetal Alchemist: Brotherhood",
        img: "https://s4.anilist.co/custom/bg/5114-1ZfM1I8rT0hR.jpg",
        genre: "Action, Adventure, Fantasy",
        type: "TV Series",
        status: "Completed",
        totalEps: 64,
        Trend: "T",
        score: "9.1",
        synopsis: "After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life. Now they seek the Philosopher's Stone to restore their bodies."
    },
    {
        id: "hunterxhunterundone",
        title: "Hunter x Hunter (2011)",
        img: "https://s4.anilist.co/custom/bg/11061-v0X2jU38yT71.jpg",
        genre: "Action, Adventure, Fantasy",
        type: "TV Series",
        status: "Completed",
        totalEps: 148,
        Trend: "N",
        score: "9.0",
        synopsis: "Hunters devote themselves to accomplishing hazardous tasks, all from traversing the world's uncharted territories to locating rare items and monsters. Before beginning his journey, Gon Freecss must pass the Hunter Examination, a notoriously difficult selection process. There, he befriends Kurapika, Leorio, and Killua."
    },
    {
        id: "erased",
        title: "ERASED",
        img: "https://s4.anilist.co/custom/bg/21234-u9qR00I443oZ.jpg",
        genre: "Mystery, Psychological, Supernatural",
        type: "TV Series",
        status: "Completed",
        totalEps: 12,
        Trend: "N",
        score: "8.3",
        synopsis: "When tragedy is about to strike, Satoru Fujinuma finds himself sent back several minutes before the accident occurs. The detached, 29-year-old manga artist has taken advantage of this powerful and mysterious phenomenon, which he calls 'Revival,' to save many lives. But when he is wrongly accused of a murder, he is sent back 18 years into the past."
    },
{
        id: "kaijuno8",
        title: "Kaiju No. 8",
        img: "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2025/06/kaiju-no-8-season-2-key-visual-cropped.jpg",
        genre: "Action, Sci-Fi, Shonen",
        type: "TV Series",
        status: "Ongoing",
        totalEps: 12,
        Trend: "T",
        score: "9.1",
        synopsis: "In a Japan plagued by monstrous creatures known as Kaiju, Kafka Hibino works a dead-end job cleaning up the aftermath of their battles until a bizarre encounter gives him the power to become one himself."
    },
    {
        id: "lotm",
        title: "Lord of the Mysteries",
        img: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx133989-1pT8y2R0yG90.jpg",
        genre: "Mystery, Supernatural, Fantasy",
        type: "TV Series",
        status: "Upcoming",
        totalEps: 12,
        Trend: "T",
        score: "N/A",
        synopsis: "Waking up to find himself reincarnated in a Victorian-era world filled with machinery, cannons, and supernatural powers, Klein Moretti becomes a Beyonder to survive and uncover the mysteries of this strange new world."
    },
    {
        id: "mobpsycho100",
        title: "Mob Psycho 100",
        img: "https://m.media-amazon.com/images/M/MV5BYzU3NDM4ZjgtY2UyMi00YTczLTgyNDEtMjBiMDJlOGUxNjcxXkEyXkFqcGc@._V1_.jpg",
        genre: "Action, Comedy, Supernatural, School, Shonen",
        type: "TV Series",
        status: "Completed",
        totalEps: 37,
        Trend: "N",
        score: "8.8",
        synopsis: "Shigeo 'Mob' Kageyama is a seemingly ordinary middle school boy, but he is a powerful Esper with immense psychic abilities. To keep his powers in check, Mob works as an assistant to Reigen Arataka, a self-proclaimed psychic who is secretly a fraud."
    },
    {
        id: "onepiece",
        title: "One Piece",
        img: "https://i.redd.it/0u2aefrzacmc1.jpeg",
        genre: "Adventure, Action, Fantasy, Shonen",
        type: "TV Series",
        status: "Ongoing",
        totalEps: 1100,
        Trend: "T",
        score: "9.0",
        synopsis: "One Piece follows the adventures of Monkey D. Luffy and his pirate crew, the Straw Hat Pirates, as he searches for the ultimate treasure known as 'One Piece' to become the King of the Pirates."
    },
    {
        id: "sakamotodays",
        title: "Sakamoto Days",
        img: "https://a.storyblok.com/f/178900/1080x1350/73f019de0e/sakamoto-days-part-2-key-visual.jpg/m/filters:quality(95)format(webp)",
        genre: "Action, Comedy, Shonen, Crime",
        type: "TV Series",
        status: "Upcoming",
        totalEps: 22,
        Trend: "T",
        score: "8.2",
        synopsis: "Taro Sakamoto was once the greatest hitman of all time, feared by the entire criminal underworld. But one day, he fell in love, got married, and retired to live a peaceful life as a family man who runs a convenience store."
    },
    {
        id: "sololeveling",
        title: "Solo Leveling",
        img: "https://images.ctfassets.net/4cd45et68cgf/5wO1320i25V50k2YJahKSc/d3d1354366d3a54a2435520a06806584/SoloLeveling_KeyArt1_CR.jpg",
        genre: "Action, Fantasy, Adventure",
        type: "TV Series",
        status: "Completed",
        totalEps: 12,
        Trend: "T",
        score: "8.4",
        synopsis: "In a world where hunters with magical abilities fight deadly monsters, Sung Jinwoo, the weakest hunter, discovers a secret quest that will change his destiny forever."
    },
    {
        id: "summertimerendering",
        title: "Summer Time Rendering",
        img: "https://www.animegeek.com/wp-content/uploads/2022/07/Summertime-Render-Part-2-Anime-Key-Visual-July-2022-724x1024.jpg",
        genre: "Mystery, Supernatural, Thriller, Suspense",
        type: "TV Series",
        status: "Completed",
        totalEps: 25,
        Trend: "N",
        score: "8.5",
        synopsis: "Upon hearing of Ushio's death, Shinpei returns to his hometown of Wakayama City on Hitogashima and reunites with his childhood friend's family. The funeral goes smoothly, but under the surface, something strange is brewing on the island."
    },
    {
        id: "takopioriginalsin",
        title: "Takopi's Original Sin",
        img: "https://media.trakt.tv/images/shows/000/276/728/posters/medium/a20aafacb8.jpg.webp",
        genre: "Drama, Psychological, Sci-Fi",
        type: "Manga (Short Series)",
        status: "Completed",
        totalEps: 2,
        Trend: "N",
        score: "8.5",
        synopsis: "Takopi is a happy alien from the planet Happy who comes to Earth to spread joy. He encounters Shizuka Kagawa, a girl burdened with loneliness and despair, and attempts to help her with his 'Happy Tools.'"
    },
    {
        id: "tobeherox",
        title: "To Be Hero X",
        img: "https://m.media-amazon.com/images/M/MV5BYmZjNzBhYjYtMzY1MS00M2U1LWFjZGQtY2RmY2FiNWE5YzkwXkEyXkFqcGc@._V1_.jpg",
        genre: "Action, Superpower, Fantasy, Comedy, Shonen",
        type: "TV Series",
        status: "Upcoming",
        totalEps: 12,
        Trend: "N",
        score: "7.5",
        synopsis: "The successor to the To Be Hero series, To Be Hero X is based on the popular Chinese comic 'To Be Hero' and follows new protagonists in a world brimming with bizarre superpowers and intense, comedic action."
    },
    {
        id: "vinlandsaga",
        title: "Vinland Saga",
        img: "https://m.media-amazon.com/images/M/MV5BZDA3NDNjYmUtNjQxMS00OTdkLThlMzAtZTM0NWJiMTliZGE1XkEyXkFqcGc@._V1_.jpg",
        genre: "Action, Adventure, Drama, Historical",
        type: "TV Series",
        status: "Completed",
        seasons: [24, 24],
        Trend: "T",
        score: "8.8",
        synopsis: "Raised by the Vikings who murdered his family, Thorfinn became a terrifying warrior, forever seeking to kill the band's leader, Askeladd, and avenge his father. Sustaining Thorfinn through his ordeal are his pride in his family and his dreams of a fertile westward land, a land without war or slavery... the land Leif called Vinland."
    },
    {
        id: "violetevergarden",
        title: "Violet Evergarden",
        img: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx21827-10F6m50H4GJK.png",
        genre: "Drama, Fantasy, Slice of Life",
        type: "TV Series",
        status: "Completed",
        totalEps: 13,
        Trend: "N",
        score: "8.6",
        synopsis: "Caught up in the bloodshed of the Great War, Violet Evergarden was raised for the sole purpose of decimating enemy lines. Now, working as an Auto Memory Doll to transcribe people's thoughts and feelings into letters, she begins to understand the final words left to her by the person she held dearest: 'I love you.'"
    },
    {
        id: "windbreaker",
        title: "WIND BREAKER",
        img: "https://m.media-amazon.com/images/M/MV5BMjY5YzE1NzQtOTUzNC00MmIwLWI5OWYtNWIzMDhlNzU4NzUzXkEyXkFqcGc@._V1_.jpg",
        genre: "Action, School, Shonen",
        type: "TV Series",
        status: "Ongoing",
        totalEps: 13,
        Trend: "T",
        score: "8.0",
        synopsis: "Haruka Sakura wants nothing to do with weaklings—he's only interested in the strongest of the strong. He's just started at Furin High School, a school of degenerates known only for their brawling strength. But Furin's students are actually town protectors, and Haruka must figure out what fighting really means."
    },
    {
        id: "tokyorevengers",
        title: "Tokyo Revengers",
        img: "https://m.media-amazon.com/images/M/MV5BNGU3YzdhMWEtMGRkMC00MzY2LThkOGEtMDFmZDE0NGQxYzFjXkEyXkFqcGc@._V1_.jpg",
        genre: "Action, Sci-Fi, Drama, School, Shonen, Time Travel",
        type: "TV Series",
        status: "Ongoing",
        totalEps: 50,
        Trend: "T",
        score: "7.7",
        synopsis: "Takemichi Hanagaki learns that his middle school ex-girlfriend, Hinata Tachibana, and her younger brother, Naoto, have been murdered by the ruthless Tokyo Manji Gang. After a near-death experience, Takemichi suddenly travels 12 years back in time to his middle school days."
    }
],